### PR TITLE
fixing suave binding

### PR DESCRIPTION
**Pull request by haf**

### CODE REVIEW

**Comment by forki** [comment]
mhm. still no luck.

**Comment by forki** [comment]
this is what I tried: https://github.com/forki/suaveondocker/blob/master/README.md

**Comment by haf** [comment]
Alright, let me set up docker on this machine...

**Comment by haf** [comment]
```
➜  ~  docker run --rm -d -p 8080:8080 forki/suave
➜  ~  docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
default   *        virtualbox   Running   tcp://192.168.99.100:2376
➜  ~  sudo nmap -sS 192.168.99.100
Password:

Starting Nmap 6.47 ( http://nmap.org ) at 2015-11-02 19:35 CET
Nmap scan report for 192.168.99.100
Host is up (0.0013s latency).
Not shown: 998 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
8080/tcp open  http-proxy
MAC Address: 08:00:27:22:5C:6B (Cadmus Computer Systems)

Nmap done: 1 IP address (1 host up) scanned in 0.32 seconds
➜  ~  curl http://192.168.99.100:8080
Hello World!%                                                                                                                                                     
➜  ~  docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
5fe06d6dd64a        67806a66923b        "/bin/bash fsharpi he"   4 minutes ago       Up 4 minutes        0.0.0.0:8080->8080/tcp   high_morse
➜  ~  docker inspect -f '{{json .Config.Cmd}}' 5fe06d6dd64a
["fsharpi","helloworld.fsx"]

```

@forki Does that solve your problem?

**Comment by forki** [comment]
Mhm will try tomorrow. Thx

**Pull request merged**
